<?php
$Menu = array (
    array('Title' => 'Two For Twenty',
        'ImageLoc' => './img/main/2for20.jpg',
        'Link' => './?category=twofor',
        array('Title' => 'Appetizers',
            'ImageLoc' => './img/twofor/mozzarella_sticks.jpg',
            'Link' => './page.php',
            array('Title' => 'Mozzarella Sticks',
                'ImageLoc' => './img/twofor/app/mozzarella_sticks.jpg'),
            array('Title' => 'Crunchy Onion Rings',
                'ImageLoc' => './img/twofor/onion_rings.jpg'),
            array('Title' => 'Two Side Salads(House or Caesar)',
                'ImageLoc' => './img/twofor/caesar_salad.jpg')),
        array('Title' => 'Entrees',
            'ImageLoc' => 'llama',
            array('Title' => 'Three-Cheese Chicken Penne', 'ImageLoc' => './img/twofor/caesar_salad.jpg'),
            array('Title' => 'Chicken Tenders Basket', 'ImageLoc' => './img/twofor/chicken_tend.jpg'),
            array('Title' => 'The American Standard', 'ImageLoc' => './img/twofor/allinburger.jpg'))
    ),
    array('Title' => 'Better For You',
        'ImageLoc' => './img/main/betterforyou.jpg',
        array('Title' => 'The Smarter Choice',
            'ImageLoc' => 'llama',
            array('Title' => 'Hot Shot Whiskey Chicken', 'ImageLoc' => './img/better4u/bourbon_chicken.jpg'),
            array('Title' => 'Savory Cedar Salmon', 'ImageLoc' => './img/better4u/salmon.jpg'),
            array('Title' => 'Shrimp Wonton Stir-Fry', 'ImageLoc' => './img/better4u/shrimpWonton.jpg'))
    ),
    array('Title' => 'Beverages',
        'ImageLoc' => './img/main/beverages.jpg',
        'Link' => '',
        array('Title' => 'Beers',
            'ImageLoc' => './img/main/beers.jpg',
            'Link'=>'',
            array('Title' => 'Neighborhood Favorites',
                'ImageLoc' => './img/main/beer.jpg',
                'Link' => ''
            ),
            array('Title' => 'Wines',
                'ImageLoc' => './img/main/wines.jpg',
                'Link' => '')
        ),
        array('Title' => 'Refreshments',
            'ImageLoc' => './img/refreshments.jpg',
            'Link' => '',
            array( 'Title' => 'Tea',
                'ImageLoc' => './img/tea.jpg',
                'Link' => ''),
            array('Title' => 'Lemonaid',
                'ImageLoc' => './img/lemonades.jpg',
                'Link' => ''),
            array('Title' => 'Lime-aids',
                'ImageLoc' => './img/limeades.jpg',
                'Link' => '')
        )
    ),
    array('Title' => 'Burgers',
        'ImageLoc' => './img/main/burgers.jpg',
        'Link' => '',
        array('Title' => 'Mushroom',
            'ImageLoc' => './img/burger_mushroomswiss.jpg',
            'Link' => ''),
        array('Title' => 'American',
            'ImageLoc' => './img/burger_american.jpg',
            'Link' => ''),
        array('Title' => 'TripleBacon',
            'ImageLoc' => './img/burger_triplebacon.jpg',
            'Link' => '')),
    array('Title' => 'Desserts',
        'ImageLoc' => './img/main/desserts.jpg',
        'Link' => '',
        array('Title' => 'TripleChoc',
            'ImageLoc' => './img/main/trip_choc.jpg',
            'Link' => ''),
        array('Title' => 'MapleBlonde',
            'ImageLoc' => './img/main/maple_blondie.jpg',
            'Link' => ''),
        array('Title' => 'AppleCheeseCake',
            'ImageLoc' => './img/main/apple_cheesecake.jpg',
            'Link' => '')
    ),
    array('Title' => 'MainEntrees',
        'ImageLoc' => './img/main/entree_main_dishes.jpg',
        'Link' => '',
        array('Title' => 'Steak',
            'ImageLoc' => './img/mainEntrees/steak.jpg',
            'Link' => '',
            array('Title' => 'GrilledOnionSirloin',
                'ImageLoc' => './img/mainEntrees/grilled_onion_sirloin.jpg',
                'Link' => ''),
            array('Title' => 'Sirloin',
                'ImageLoc' => './img/mainEntrees/sirloin.jpg',
                'Link' => ''),
            array('Title' => 'PepperSirloin',
                'ImageLoc' => './img/mainEntrees/pepper_sirloin.jpg',
                'Link' => '')),
        array('Title' => 'Ribs',
            'ImageLoc' => './img/mainEntrees/ribs.jpg',
            'Link' => '',
            array('Title' => 'Riblets',
                'ImageLoc' => './img/mainEntrees/riblets.jpg',
                'Link' => ''),
            array('Title' => 'BabyBack',
                'ImageLoc' => './img/mainEntrees/babyback_ribs.jpg',
                'Link' => '')),
        array('Title' => 'Chicken',
            'ImageLoc' => './img/mainEntrees/chicken.jpg',
            'Link' => '',
            array('Title' => 'BrewHouse',
                'ImageLoc' => './img/mainEntrees/brewhouse_chicken.jpg',
                'Link' => ''),
            array('Title' => 'BurbonChicken',
                'ImageLoc' => './img/mainEntrees/bourbon_chicken.jpg',
                'Link' => ''),
            array('Title' => 'ChickenTend',
                'ImageLoc' => './img/mainEntrees/chicken_tenders.jpg',
                'Link' => '')),
    ),
​
array('Title' => 'Lunch Combos',
    'ImageLoc' => './img/main/lunch_combos.jpg',
    'Link' => '',
    array('Title' => 'Tomato Basil Soup +  French Onion Soup',
        'ImageLoc' => './img/lunchCombos/meatballs.jpg',
        'Link' => ''),
    array('Title' => 'House Salad(contains bacon) + Clubhouse Grille',
        'ImageLoc' => './img/lunchCombos/oriental_salad.jpg',
        'Link' => ''),
    array('Title' => 'Chicken Fajita Rollup + Shrimp Scampi Linguine',
        'ImageLoc' => './img/lunchCombos/shrimp.jpg',
        'Link' => '')),
​
    array('Title' => 'Salads',
        'ImageLoc' => './img/main/salads.jpg',
        'Link' => '',
        array('Title' => 'ThaiShrimp',
            'ImageLoc' => './img/salads/ThaiShrimp.jpg',
            'Link' => ''),
        array('Title' => 'FiestaChicken',
            'ImageLoc' => './img/salads/FiestaChicken.jpg',
            'Link' => ''),
        array('Title' => 'ChickenCeasar',
            'ImageLoc' => './img/salads/ChickenCeasar.jpg',
            'Link' => '')
    ),
    array('Title' => 'PubDiet',
        'ImageLoc' => 'llama',
        'Link' => '',
        array('Title' => 'ShrimpWonton',
            'ImageLoc' => './img/pubdiet/ShrimpWonton.jpg',
            'Link' => ''),
        array('Title' => 'SirloinStout',
            'ImageLoc' => './img/pubdiet/SirloinStout.jpg',
            'Link' => ''),
        array('Title' => 'CedarChicken',
            'ImageLoc' => './img/pubdiet/CedarChicken.jpg',
            'Link' => '')
    ),
    array('Title' => 'Handhelds',
        'ImageLoc' => './img/main/handhelds.jpg',
        'Link' => '',
        array('Title' => 'New Triple Hog Dare Ya',
            'ImageLoc' => './img/Handhelds/triple_hog_dare_ya.jpg',
            'Link' => ''),
        array('Title' => 'New Kickin Turkey Stacker',
            'ImageLoc' => './img/Handhelds/turkey_stacker.jpg',
            'Link' => ''),
        array('Title' => 'American BLT',
            'ImageLoc' => './img/Handhelds/blt.jpg',
            'Link' => '')),
    array('title' => 'Kids',
        'ImageLoc' => './img/kid1.jpg',
        'Link' => './?category=kids',
        array('Title' => 'Kid1',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'Kid2',
            'ImageLoc' => 'llama',
            'Link' => ''),
        array('Title' => 'Kid3',
            'ImageLoc' => 'llama',
            'Link' => ''))
);
?>